set dotenv-load := true
down:
    terraform apply -var 'enable_green_env=false' -var 'enable_blue_env=false' -var
    'traffic_distribution=split'

deploy-blue:
    terraform apply -var 'traffic_distribution=blue' -var 'enable_green_env=false'

deploy-green:
    terraform apply -var 'traffic_distribution=blue' -var 'enable_blue_env=false'

deploy-split:
    terraform apply -var 'traffic_distribution=split'
