down:
    terraform apply -var 'enable_green=false' -var 'enable_blue=false'

blue:
    terraform apply -var 'enable_green=false'

green:
    terraform apply -var 'enable_blue=false'

both:
    terraform apply
